#
# this is included in the secrets as helm does not merge config files
# EGI Check-in configuration is also in secrets
#proxy:
#  service:
#    type: NodePort

hub:
  extraEnv:
    OAUTH2_AUTHORIZE_URL: https://aai.egi.eu/oidc/authorize
    OAUTH2_TOKEN_URL: https://aai.egi.eu/oidc/token
  db:
    pvc:
      annotations: {volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"}

ingress:
  enabled: true
  annotations: {kubernetes.io/ingress.class: traefik}
  hosts: [jupyterhub.fedcloud-tf.fedcloud.eu]

singleuser:
  lifecycleHooks:
    postStart:
      exec: { "command": ["/bin/sh", "-c", "ln -s /persistent $HOME/persistent"]}
  storage:
    capacity: 1Gi
    homeMountPath: /persistent
    dynamic:
      storageClass: "managed-nfs-storage"
      pvcNameTemplate: claim-{userid}{servername}
      volumeNameTemplate: vol-{userid}{servername}
      storageAccessModes: ["ReadWriteMany"]
